### ISSUE TITLE
Can't open it in Chrome (MacOS X)

### ISSUE THREAD

**Issue by xDGameStudios** [etodd/dialogger#1]
I learnt about the editor in GDC youtube channel and I was trying to mess a little with the editor... (add new types of nodes...) but I'm having trouble opening the editor.. I cloned the repository and open the HMTL with chrome and it doesn't work. What am I doing wrong?

**Comment by etodd** [comment]
Follow [the instructions](https://github.com/etodd/dialogger#running) in the readme! This is designed to run as a standalone desktop program rather than a web app, in order to allow full file open/save support.
